services:
  netronome:
    image: 'ghcr.io/autobrr/netronome:v0.8.0'
    volumes:
      - '${APP_DATA_DIR}/data:/data'
      - '${APP_DATA_DIR}/data/config/netronome/config.toml:/data/.config/netronome/config.toml'
    x-runtipi:
      internal_port: 7575
      is_main: true
x-runtipi:
  schema_version: 2