services:
  nextexplorer:
    image: 'nxzai/explorer:latest'
    volumes:
      - '${APP_DATA_DIR}/data/config:/config'
      - '${APP_DATA_DIR}/data/cache:/cache'
      - '${FILES_PATH}:/mnt/Files'
    environment:
      - 'NODE_ENV=production'
      - 'PUBLIC_URL=${APP_PROTOCOL}://${APP_DOMAIN}'
      - 'SESSION_SECRET=${SESSION_SECRET}'
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
    x-runtipi:
      internal_port: 3000
      is_main: true
x-runtipi:
  schema_version: 2
