services:
  stremio_server:
    environment:
    - FFMPEG_BIN=/bin/ffmpeg
    - FFPROBE_BIN=/bin/ffprobe
    image: stremio/server:v4.20.19
    x-runtipi:
      internal_port: 11470
      is_main: true
x-runtipi:
  schema_version: 2
