services:
  postgresql:
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=fake
    - POSTGRES_DB=bewcloud
    image: postgres:17
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
    - bewcloud-db:/var/lib/postgresql/data
    x-runtipi:
      internal_port: 5432
  website:
    image: ghcr.io/bewcloud/bewcloud:v2.3.1
    volumes:
    - ./data-files:/app/data-files
    - ./bewcloud.config.ts:/app/bewcloud.config.ts
    x-runtipi:
      internal_port: 8000
      is_main: true
x-runtipi:
  schema_version: 2
