services:
  erugo:
    image: 'wardy784/erugo:0.0.34-app-api'
    volumes:
      - '${APP_DATA_DIR}/data/storage:/var/www/html/storage'
    x-runtipi:
      internal_port: 80
      is_main: true
x-runtipi:
  schema_version: 2
