name: Nettoyer anciennes runs
on:
 # schedule:
 #   - cron: '0 0 1 * *'  # 1er du mois à minuit
  workflow_dispatch:  # Manuel aussi

jobs:
  delete:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # Nécessaire pour API
      contents: read
    steps:
      - name: Supprimer runs anciennes
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 10
          keep_minimum_runs: 6
