services:
  wordpress:
    image: 'wordpress:6.8.2'
    volumes:
      - '${APP_DATA_DIR}/data/wordpress:/var/www/html'
    environment:
      - 'WORDPRESS_DB_HOST=wordpress-db'
      - 'WORDPRESS_DB_NAME=wordpress'
      - 'WORDPRESS_DB_USER=tipi'
      - 'WORDPRESS_DB_PASSWORD=${DB_PASSWORD}'
    depends_on:
      - 'wordpress-db'
    x-runtipi:
      internal_port: 80
      is_main: true
  wordpress-db:
    image: 'mariadb:12'
    volumes:
      - '${APP_DATA_DIR}/data/mariadb:/var/lib/mysql'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
      - 'MYSQL_DATABASE=wordpress'
      - 'MYSQL_USER=tipi'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
x-runtipi:
  schema_version: 2
