services:
  wordpress:
    depends_on:
    - wordpress-db
    environment:
    - WORDPRESS_DB_HOST=wordpress-db
    - WORDPRESS_DB_NAME=wordpress
    - WORDPRESS_DB_USER=tipi
    - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    image: wordpress:6.9.4
    volumes:
    - ${APP_DATA_DIR}/data/wordpress:/var/www/html
    x-runtipi:
      internal_port: 80
      is_main: true
  wordpress-db:
    environment:
    - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    - MYSQL_DATABASE=wordpress
    - MYSQL_USER=tipi
    - MYSQL_PASSWORD=${DB_PASSWORD}
    image: mariadb:12
    volumes:
    - ${APP_DATA_DIR}/data/mariadb:/var/lib/mysql
x-runtipi:
  schema_version: 2
